// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID        int64
	StartTime pgtype.Timestamp
	EndTime   pgtype.Timestamp
	Email     string
	CreateAt  pgtype.Timestamp
}
